### ISSUE TITLE
在网易云音乐能发布吗？

### ISSUE THREAD

**Issue by sanyucz** [li-xinyang/SS_EnglishGrammar#1]

**Comment by li-xinyang** [comment]
可以，我晚上回家研究下。发布在播客平台主要的目的是可以调速。

**Comment by awpsawps12** [comment]
网易云音乐主播频道已经开通了，地址为： http://music.163.com/m/radio?id=350225447
也可以扫码进入：
![image](https://user-images.githubusercontent.com/12215558/29261251-28df5d2a-8101-11e7-83d6-a0c544767fae.png)
